# -*- coding: utf-8 -*-
"""PrezzoBenzinaBandieraEconomica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cNeC-lSP7FOg8HIBMSo89rRnt9VY8m0I
"""

import pandas as pd

import seaborn as sns

import datetime
#from datetime import datetime
#import datetime as dt

import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation,PillowWriter

import imageio

"""https://www.mise.gov.it/index.php/it/open-data/elenco-dataset/carburanti-prezzi-praticati-e-anagrafica-degli-impianti"""

from google.colab import drive 
drive.mount('/content/gdrive')

prezzoBenzina = pd.read_csv('gdrive/My Drive/DataAnalysis/PrezzoBenzina/prezzo_alle_8.csv',delimiter=';',skiprows=1)

prezzoBenzina

impianti = pd.read_csv('gdrive/My Drive/DataAnalysis/PrezzoBenzina/anagrafica_impianti_attivi.csv', on_bad_lines='skip',delimiter=';',skiprows=1)

impianti

df = pd.merge(prezzoBenzina, impianti, how='left', on ='idImpianto')
df

df.dtypes

df['dtComu']= pd.to_datetime(df['dtComu'])
df

df['dtComu'] = pd.to_datetime(df['dtComu'].dt.strftime('%d/%m/%y'))
df

prova=df.groupby(['Bandiera', 'dtComu'])["prezzo"].mean()
prova

df2=impianti.groupby(['Bandiera'],as_index=False)['Indirizzo'].count()
df2

df2 = df2[df2.Indirizzo >= 1000]
df2

df_best=df[df['Bandiera'].isin(df2['Bandiera'])]
df_best

df_best.dtypes

df_best_medio=df_best.groupby(['Bandiera','dtComu'],as_index=False)['prezzo'].mean()
df_best_medio

sns.relplot(data=df_best_medio,x='dtComu',y='prezzo',hue='Bandiera',height=4, aspect=3,kind='line')

df_best_medio_dicembre = df_best_medio[df_best_medio.dtComu < "2022-12-30"]
g = sns.relplot(data=df_best_medio_dicembre,x='dtComu',y='prezzo',hue='Bandiera',height=4,aspect=3,kind='line')
g.set_axis_labels("Data (aaaa-mm-gg)","Prezzo benzina")
images_dir = 'gdrive/My Drive/DataAnalysis/PrezzoBenzina/imagesBandiera'
plt.savefig(f"{images_dir}/dicembre.png")

df_best_medio_gennaio = df_best_medio[df_best_medio.dtComu < "2023-01-30"]
g = sns.relplot(data=df_best_medio_gennaio,x='dtComu',y='prezzo',hue='Bandiera',height=4,aspect=3,kind='line')
g.set_axis_labels("Data (aaaa-mm-gg)","Prezzo benzina")
images_dir = 'gdrive/My Drive/DataAnalysis/PrezzoBenzina/imagesBandiera'
plt.savefig(f"{images_dir}/gennaio.png")

df_best_medio_febbraio = df_best_medio[df_best_medio.dtComu < "2023-02-28"]
g = sns.relplot(data=df_best_medio_febbraio,x='dtComu',y='prezzo',hue='Bandiera',height=4,aspect=3,kind='line')
g.set_axis_labels("Data (aaaa-mm-gg)","Prezzo benzina")
images_dir = 'gdrive/My Drive/DataAnalysis/PrezzoBenzina/imagesBandiera'
plt.savefig(f"{images_dir}/febbraio.png")

df_best_medio_marzo = df_best_medio[df_best_medio.dtComu < "2023-03-30"]
g = sns.relplot(data=df_best_medio_marzo,x='dtComu',y='prezzo',hue='Bandiera',height=4,aspect=3,kind='line')
g.set_axis_labels("Data (aaaa-mm-gg)","Prezzo benzina")
images_dir = 'gdrive/My Drive/DataAnalysis/PrezzoBenzina/imagesBandiera'
plt.savefig(f"{images_dir}/marzo.png")

df_best_medio_aprile = df_best_medio[df_best_medio.dtComu < "2023-04-30"]
g = sns.relplot(data=df_best_medio_aprile,x='dtComu',y='prezzo',hue='Bandiera',height=4,aspect=3,kind='line')
g.set_axis_labels("Data (aaaa-mm-gg)","Prezzo benzina")
#g.set_titles("Prezzo benzina 01/20/2022-30/04/2023")
images_dir = 'gdrive/My Drive/DataAnalysis/PrezzoBenzina/imagesBandiera'
plt.savefig(f"{images_dir}/aprile.png")

df_best_mean=df_best.groupby('Bandiera',as_index=False)['prezzo'].mean()
df_best_mean.sort_values(['prezzo'])